export const ui = {
  card: {
    padding: 16,
    borderRadius: "var(--radius)",
    background: "var(--card)",
    border: "1px solid var(--border)",
    backdropFilter: "blur(10px)",
  },
  cardSoft: {
    borderRadius: "var(--radius)",
    background: "var(--card2)",
    border: "1px solid var(--border)",
  },
  title: {
    margin: 0,
    fontSize: 18,
    letterSpacing: 0.2,
  },
  muted: {
    opacity: 0.85,
    color: "var(--muted)",
  },
  input: {
    padding: "14px 14px",
    borderRadius: 16,
    border: "1px solid var(--border)",
    background: "rgba(0,0,0,0.25)",
    color: "var(--text)",
    outline: "none",
    fontSize: 16,
},
  button: {
    padding: "14px 18px",
    borderRadius: 18,
    border: "none",
    background: "linear-gradient(135deg, var(--accent), var(--accent2))",
    color: "#0b0d12",
    fontWeight: 900,
    fontSize: 17,
    cursor: "pointer",
},
  buttonGhost: {
    padding: "10px 12px",
    borderRadius: 14,
    border: "1px solid var(--border)",
    background: "rgba(255,255,255,0.06)",
    color: "var(--text)",
    cursor: "pointer",
  },
  danger: {
    border: "1px solid rgba(255,80,80,0.55)",
    background: "rgba(255,80,80,0.12)",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "rgba(255,255,255,0.06)",
    fontSize: 12,
    color: "var(--muted)",
  },
};
